micronaut:
  application:
    name: realtime-messaging

endpoints:
  all:
    enabled: true
  health:
    enabled: true
    sensitive: false

logger:
  levels:
    root: INFO
    messaging: INFO
    messaging.ConnectionRegistry: DEBUG
    org.flywaydb: DEBUG
    io.micronaut.jdbc: DEBUG